### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by iam-py-test** [DariusIurca/RFNBL-Romanian-Fake-News-Block-List#1]
https://github.com/DariusIurca/RFNBL/blob/47bbf7a523504e7ccad603d87843de1ce4802fe9/RFNBL.txt#L13

Should start with a comment, as uBo/AdGuard would treat that as a invalid filter, and it may cause issues
Thank you!

**Comment by DariusIurca** [comment]
Solved, thanks!
